### PR TITLE
Add formatter support

### PR DESCRIPTION
**Pull request by dmikurube**
After #52, it finally adds formatter support in this library. The formatter works almost the same as `Time#strftime` in (C)Ruby.
https://docs.ruby-lang.org/en/2.5.0/Time.html#method-i-strftime

The usage would be :
`String s = RubyDateTimeFormatter.ofPattern("<format>").format(<java.time object>);`

### CODE REVIEW

**Review by shroman — COMMENTED** [review]
@dmikurube I think it'll be safer to have more test coverage for `FormatterWithContext`. About 20% now.

**Comment by dmikurube** [comment]
@shroman I don't think so. 90% instructions of `FormatterWithContext` are already covered by `crubyTest`.

**Comment by shroman** [comment]
I see.

**Review by shroman — APPROVED** [review]

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
